

def get_location(start, end=None):
    if end:
        return {'type': 'range',
                'start': get_location(start),
                'end': get_location(end)}
    else:
        return {'type': 'point',
                'position': start}


VARIANTS = {
    '4del': {'type': 'deletion',
             'source': 'reference',
             'location': get_location(4)},
    '4_5del': {'type': 'deletion',
               'source': 'reference',
               'location': get_location(4, 5)},
    '3_5del': {'type': 'deletion',
               'source': 'reference',
               'location': get_location(3, 5)},
    '3_4del': {'type': 'deletion',
               'source': 'reference',
               'location': get_location(3, 4)},
    '10del': {'type': 'deletion',
              'source': 'reference',
              'location': get_location(10)},
    '(10_15)del': {'type': 'deletion',
                   'source': 'reference',
                   'location': {'type': 'range',
                                'uncertain': True,
                                'start': {'type': 'point',
                                          'position': 10},
                                'end': {'type': 'point',
                                        'position': 15}}},
    '(10_20)_(30_40)del': {'type': 'deletion',
                           'source': 'reference',
                           'location': {'type': 'range',
                                        'start': {'type': 'range',
                                                  'uncertain': True,
                                                  'start': {'type': 'point',
                                                            'position': 10},
                                                  'end': {'type': 'point',
                                                          'position': 20}},
                                        'end': {'type': 'range',
                                                'uncertain': True,
                                                'start': {'type': 'point',
                                                          'position': 30},
                                                'end': {'type': 'point',
                                                        'position': 40}}}},
    '(?_10)_(100_?)del': {'type': 'deletion',
                          'source': 'reference',
                          'location': {'type': 'range',
                                       'start': {'type': 'range',
                                                 'uncertain': True,
                                                 'start': {'type': 'point',
                                                           'uncertain': True},
                                                 'end': {'type': 'point',
                                                         'position': 10}},
                                       'end': {'type': 'range',
                                               'uncertain': True,
                                               'start': {'type': 'point',
                                                         'position': 100},
                                               'end': {'type': 'point',
                                                       'uncertain': True}}}},
    '4A>T': {'type': 'substitution',
             'source': 'reference',
             'location': get_location(4)},
    '3_4A>T': {'type': 'substitution',
               'source': 'reference',
               'location': get_location(3, 4)},
    '4_5insT': {'type': 'insertion',
                'source': 'reference',
                'location': get_location(4, 5),
                'inserted': [{'sequence': 'T',
                              'source': 'description'}]},
    '4_4insT': {'type': 'insertion',
                'source': 'reference',
                'location': get_location(4, 4),
                'inserted': [{'sequence': 'T',
                              'source': 'description'}]},
    '4_5ins7_8': {'type': 'insertion',
                  'source': 'reference',
                  'location': get_location(4, 5),
                  'inserted': [{'source': 'reference',
                                'location': get_location(7, 8)}]},
    '4_4ins6_8': {'type': 'insertion',
                  'source': 'reference',
                  'location': get_location(4, 4),
                  'inserted': [{'source': 'reference',
                                'location': get_location(6, 8)}]},
    '4_5ins[7_8;10_20]': {'type': 'insertion',
                          'source': 'reference',
                          'location': get_location(4, 5),
                          'inserted': [{'source': 'reference',
                                        'location': get_location(7, 8)},
                                       {'source': 'reference',
                                        'location': get_location(10, 20)}]},
    '4_4ins[6_8;9_20]': {'type': 'insertion',
                         'source': 'reference',
                         'location': get_location(4, 4),
                         'inserted': [{'source': 'reference',
                                       'location': get_location(6, 8)},
                                      {'source': 'reference',
                                       'location': get_location(9, 20)}]},
    '4_5ins[7_8;10_20;T]': {'type': 'insertion',
                            'source': 'reference',
                            'location': get_location(4, 5),
                            'inserted': [{'source': 'reference',
                                          'location': get_location(7, 8)},
                                         {'source': 'reference',
                                          'location': get_location(10, 20)},
                                         {'sequence': 'T',
                                          'source': 'description'}]},
    '4_4ins[6_8;9_20;T]': {'type': 'insertion',
                           'source': 'reference',
                           'location': get_location(4, 4),
                           'inserted': [{'source': 'reference',
                                         'location': get_location(6, 8)},
                                        {'source': 'reference',
                                         'location': get_location(9, 20)},
                                        {'sequence': 'T',
                                         'source': 'description'}]},
    '4=': {'type': 'equal',
           'source': 'reference',
           'location': get_location(4)},
    '3_4=': {'type': 'equal',
             'source': 'reference',
             'location': get_location(3, 4)},
    '2_4=': {'type': 'equal',
             'source': 'reference',
             'location': get_location(2, 4)},
    '10_20=': {'type': 'equal',
               'source': 'reference',
               'location': get_location(10, 20)},
    '4dup': {'type': 'duplication',
             'source': 'reference',
             'location': get_location(4)},
    '3_4dup': {'type': 'duplication',
               'source': 'reference',
               'location': get_location(3, 4)},
    '2_4dup': {'type': 'duplication',
               'source': 'reference',
               'location': get_location(2, 4)},
    '4_5con7_8': {'type': 'conversion',
                  'source': 'reference',
                  'location': get_location(4, 5),
                  'inserted': [{'source': 'reference',
                                'location': get_location(7, 8)}]},
    '3_5con6_8': {'type': 'conversion',
                  'source': 'reference',
                  'location': get_location(3, 5),
                  'inserted': [{'source': 'reference',
                                'location': get_location(6, 8)}]},
    '4delins7_8': {'type': 'deletion_insertion',
                   'source': 'reference',
                   'location': get_location(4),
                   'inserted': [{'source': 'reference',
                                 'location': get_location(7, 8)}]},
    '3_4delins6_8': {'type': 'deletion_insertion',
                     'source': 'reference',
                     'location': get_location(3, 4),
                     'inserted': [{'source': 'reference',
                                   'location': get_location(6, 8)}]},
    '4_4delinsAA': {'type': 'deletion_insertion',
                    'source': 'reference',
                    'location': get_location(4, 4),
                    'inserted': [{'source': 'description',
                                  'sequence': 'AA'}]}
}


def get_variant(variant_key):
    return VARIANTS[variant_key]


def get_variants_tuple(input_variant, expected):
    return [VARIANTS[input_variant]], [VARIANTS[expected]]
